namespace tilecon
{
    public enum SpriteMode
    {
        ALIGN_TOP_LEFT,    ALIGN_TOP_CENTER,    ALIGN_TOP_RIGHT,
        ALIGN_MIDDLE_LEFT, ALIGN_MIDDLE_CENTER, ALIGN_MIDDLE_RIGHT,
        ALIGN_BOTTOM_LEFT, ALIGN_BOTTOM_CENTER, ALIGN_BOTTOM_RIGHT,
        RESIZE
    }
}
